// Copies self-hosted runtime assets from node_modules into public/
// (OCR, AVIF wasm, ffmpeg core). Regenerated by predev/prebuild hooks.
import { cpSync, mkdirSync, readdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

// --- OCR (tesseract) ---
const tesseractOut = join(root, 'public', 'tesseract')
mkdirSync(join(tesseractOut, 'core'), { recursive: true })
mkdirSync(join(tesseractOut, 'lang'), { recursive: true })

cpSync(
  join(root, 'node_modules/tesseract.js/dist/worker.min.js'),
  join(tesseractOut, 'worker.min.js')
)

const coreDir = join(root, 'node_modules/tesseract.js-core')
for (const name of readdirSync(coreDir)) {
  if (name.startsWith('tesseract-core') && name.includes('lstm')) {
    cpSync(join(coreDir, name), join(tesseractOut, 'core', name))
  }
}

cpSync(join(root, 'node_modules/@tesseract.js-data/eng/4.0.0_best_int'), join(tesseractOut, 'lang'), {
  recursive: true,
})
console.log('OCR assets copied to public/tesseract/')

// --- AVIF wasm (single-thread) ---
const wasmOut = join(root, 'public', 'wasm')
mkdirSync(wasmOut, { recursive: true })
const avifRoot = join(root, 'node_modules/@jsquash/avif/codec')
cpSync(join(avifRoot, 'dec/avif_dec.wasm'), join(wasmOut, 'avif_dec.wasm'))
cpSync(join(avifRoot, 'enc/avif_enc.wasm'), join(wasmOut, 'avif_enc.wasm'))
console.log('AVIF wasm copied to public/wasm/')

// --- ffmpeg.wasm core (single-thread, ~31 MB) ---
const ffmpegOut = join(root, 'public', 'ffmpeg')
mkdirSync(ffmpegOut, { recursive: true })
const ffmpegCore = join(root, 'node_modules/@ffmpeg/core/dist/esm')
cpSync(join(ffmpegCore, 'ffmpeg-core.js'), join(ffmpegOut, 'ffmpeg-core.js'))
cpSync(join(ffmpegCore, 'ffmpeg-core.wasm'), join(ffmpegOut, 'ffmpeg-core.wasm'))
console.log('ffmpeg core copied to public/ffmpeg/')
